# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7ZtpSFlncLTbiGRekMYSCY71NuInQW5

## Imports
"""

import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score, classification_report
from scipy.stats import ks_2samp
import shap
from sklearn.metrics import roc_auc_score, roc_curve, f1_score, precision_score, recall_score, classification_report

"""## Funções"""

def plot_distribuicao_target(df, variable_name, target_name):
    fig, ax1 = plt.subplots(figsize=(12, 6))

    value_counts = df[variable_name].value_counts().sort_index()
    ax1.bar(value_counts.index, value_counts.values, color='y')
    ax1.set_xlabel(variable_name)
    ax1.set_ylabel('Frequência', color='black')
    ax1.tick_params(axis='y', labelcolor='black')
    ax1.set_title(f'Distribuição da Variável {variable_name} e Número de Fraudes')

    ax2 = ax1.twinx()
    fraud_counts = df[df['Fraude'] == 1].groupby(variable_name)['Fraude'].count()
    ax2.plot(fraud_counts.index, fraud_counts.values, color='red', marker='o')
    ax2.set_ylabel('Número de Fraudes', color='black')
    ax2.tick_params(axis='y', labelcolor='black')

    plt.tight_layout()
    plt.show()

def plot_distribuicao(df, variable_name):
    plt.figure(figsize=(10, 6))
    sns.histplot(df[variable_name], kde=True, palette='deep')
    plt.title(f'Distribuição da Variável {variable_name}')
    plt.xlabel(variable_name)
    plt.ylabel('Frequência')
    plt.show()

def plotar_percentual_por_categoria(df, var, target):
    grupo = df.groupby([var, target]).size().reset_index(name='count')

    grupo_total = grupo.groupby(var)['count'].transform('sum')
    grupo['percentual'] = 100 * grupo['count'] / grupo_total

    # Plot
    plt.figure(figsize=(10, 5))
    sns.barplot(data=grupo, x=var, y='percentual', hue=target, palette='deep')
    plt.title(f"Variável '{var}' x {target}")
    plt.ylabel("Percentual %")
    plt.xlabel(f"{var}")
    plt.tight_layout()
    plt.show()

def plot_roc_curves(y_test, y_probs_test, y_val, y_probs_val):

    fpr_test, tpr_test, _ = roc_curve(y_test, y_probs_test)
    roc_auc_test = roc_auc_score(y_test, y_probs_test)

    fpr_val, tpr_val, _ = roc_curve(y_val, y_probs_val)
    roc_auc_val = roc_auc_score(y_val, y_probs_val)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr_test, tpr_test, label=f'Teste (AUC = {roc_auc_test:.2f})')
    plt.plot(fpr_val, tpr_val, label=f'Validação (AUC = {roc_auc_val:.2f})')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Curva ROC')
    plt.legend(loc='lower right')
    plt.show()

def encontrar_threshold_max_lucro(y_true, y_prob, montos, best_threshold_f1, thresholds=np.linspace(0.01, 0.99, 100)):
    balanco = []
    lucros = []

    y_true = y_true.values

    for t in thresholds:
        y_pred = (y_prob > t).astype(int)

        balanco_total = np.sum([
            +0.25 * m if (yt == 0 and yp == 0) else   # Legítimas aprovadas
            -0.25 * m if (yt == 0 and yp == 1) else   # Legítimas bloqueadas
            -1.00 * m if (yt == 1 and yp == 0) else   # Fraudes aprovadas
            +1.00 * m if (yt == 1 and yp == 1) else 0 # Fraudes detectadas
            for yt, yp, m in zip(y_true, y_pred, montos)
        ])

        balanco.append(balanco_total)

        lucro_real = np.sum([
            +0.25 * m if (yt == 0 and yp == 0) else   # Legítimas aprovadas
            # -0.25 * m if (yt == 0 and yp == 1) else   # Legítimas bloqueadas
            -1.00 * m if (yt == 1 and yp == 0) else   0 # Fraudes aprovadas
            # +1.00 * m if (yt == 1 and yp == 1) else 0 # Fraudes detectadas
            for yt, yp, m in zip(y_true, y_pred, montos)
        ])

        lucros.append(lucro_real)

    melhor_threshold = thresholds[np.argmax(lucros)]
    lucro_maximo = max(lucros)

    print(f"Melhor Threshold para Lucro: {melhor_threshold:.2f}")
    print(f"Lucro Máximo: {lucro_maximo:.2f}")

    plt.figure(figsize=(8, 5))
    plt.plot(thresholds, lucros)
    plt.xlabel("Threshold")
    plt.ylabel("Lucro Real")
    plt.title("Lucro vs Threshold")
    plt.axvline(melhor_threshold, color='red', linestyle='--', label=f"Melhor Threshold Lucro = {melhor_threshold:.2f}")
    plt.axvline(best_threshold_f1, color='blue', linestyle='--', label=f"Melhor Threshold  F1-SCORE = {best_threshold_f1:.2f}")
    plt.grid(True)
    plt.legend()
    plt.show()

    return melhor_threshold, lucro_maximo

def metricas_fraude(cm, y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    detection_rate = tp / (tp + fn) if (tp + fn) > 0 else 0
    alert_rate = fp / (tp + fp) if (tp + fp) > 0 else 0
    hit_rate = tp / (tp + fp) if (tp + fp) > 0 else 0
    rejection_rate = (tp + fp) / (tp + fp + tn + fn)  # fraudes + falsos alertas

    print("Métricas específicas de Fraude:")
    print(f"Detection Rate (Recall):     {detection_rate:.4f}")
    print(f"Alert Rate (False Alarm):    {alert_rate:.4f}")
    print(f"Hit Rate (Precision):        {hit_rate:.4f}")
    print(f"Rejection Rate (Alertas):    {rejection_rate:.4f}")

def analisar_metricas_por_decil(y_true, y_proba):
    df_score = pd.DataFrame({
        'y_true': y_true,
        'score': y_proba
    })

    df_score['decil'] = pd.qcut(df_score['score'], 10, labels=False, duplicates='drop')

    total_fraudes = df_score['y_true'].sum()
    total_transacoes = len(df_score)

    resultados = []

    for decil in range(9, -1, -1):
        grupo = df_score[df_score['decil'] == decil]
        tp = grupo['y_true'].sum()
        fp = len(grupo) - tp
        alertas = len(grupo)

        hit_rate = tp / alertas if alertas > 0 else 0
        detection_rate = tp / total_fraudes if total_fraudes > 0 else 0
        alert_rate = alertas / total_transacoes

        score_min = grupo['score'].min()*1000
        score_max = grupo['score'].max()*1000

        resultados.append({
            'Decil': f'{decil + 1}',
            'Score Mínimo': round(score_min),
            'Score Máximo': round(score_max),
            'Transações': alertas,
            'Fraudes': int(tp),
            'Hit Rate': round(hit_rate, 4),
            'Detection Rate': round(detection_rate, 4),
            'Alert Rate': round(alert_rate, 4),
        })

    return pd.DataFrame(resultados)

def calculate_profit(y_true, y_pred, amounts):
    amounts = amounts.loc[y_true.index]
    tp = np.sum((y_true == 1) & (y_pred == 1))  # Fraudes detectadas e bloqueadas (Somar e *(+1))
    fp = np.sum((y_true == 0) & (y_pred == 1))  # Transação Legítimas bloqueadas (Somar e *(-0,25))
    tn = np.sum((y_true == 0) & (y_pred == 0))  # Transação Legítimas Aprovadas (Somar e *0,25)
    fn = np.sum((y_true == 1) & (y_pred == 0))  # Fraudes Aprovada (Somar e *(-1))


    Lucro_Bruto = 0.25 * np.sum(amounts[(y_true == 0) & (y_pred == 0)])
    Save = np.sum(amounts[(y_true == 1) & (y_pred == 1)])
    Saldo_Neg = -0.25 * np.sum(amounts[(y_true == 0) & (y_pred == 1)])
    Prejuizo = -1.00 * np.sum(amounts[(y_true == 1) & (y_pred == 0)])

    print(f"Lucro: {Lucro_Bruto:.2f}") #Quanto ganhei
    print(f"Prejuizo: {Prejuizo:.2f}") # Quanto perdi por Fraude
    print(f"Save : {Save:.2f}") # Quanto salvei
    print(f"Saldo Negativo: {Saldo_Neg:.2f}") #Quanto deixei de ganhar
    print(f"Balanço Total: {Lucro_Bruto + Prejuizo + Save + Saldo_Neg:.2f}")
    print(f"Lucro Real: {Lucro_Bruto + Prejuizo:.2f}")
    return

def calculate_psi(expected, actual, bins=10):
    expected, bins = np.histogram(expected, bins=bins, density=True)
    actual, _ = np.histogram(actual, bins=bins, density=True)

    expected = np.clip(expected, 1e-10, None)
    actual = np.clip(actual, 1e-10, None)

    psi_values = (expected - actual) * np.log(expected / actual)
    return np.sum(psi_values.round(4))